### ISSUE TITLE
Is it possible to use this package in a markdown file?

### ISSUE THREAD

**Issue by qwertyjl** [fpantigny/witharrows#1]
To write notes I use markdown files in vscode. The preview is handled by mathjax. 
Do you know if it is possible to import this package there? is it possible to use this package outside of a latex project? Is there a markdown editor that can do this? Thank you.
Excuse me if this is not a WithArrows issue, but no one is able to help me online

**Comment by fpantigny** [comment]
Unfortunately, the answer is: _no_. The package `witharrows` only works in LaTeX (or, at least, in TeX).
